name: CI-dev-pipeline
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ] # to change to develop
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: lucasalt/act_base:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: "sample-score-website"
      - name: RunOne
        run: |
          echo Hello, world!
      - name: Build docker
        run: | 
          echo ---Building and starting up docker---
          docker-compose -f ./sample-score-website/docker-compose.test.yml -p testing up -d
          echo ---Containers up---s
      - name: Run test
        run: |
          echo --- Running test cases ---
          docker-compose -f ./sample-score-website/docker-compose.test-github.yml -p testing up --build --exit-code-from api-test
          echo --- Completed test cases ---
      - name: Send slack notification
        if: always()
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)    