name: CI-dev-pipeline
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ] # to change to develop
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: lucasalt/act_base:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: "sample-score-website"
      - name: RunOne
        run: |
          echo Hello, world!
      - name: Build docker
        run: | 
          echo ---Building and starting up docker---
          docker-compose -f ./sample-score-website/docker-compose.test.yml -p testing up -d
          echo ---Containers up---s
      - name: Run test
        run: |
          echo --- Running test cases ---
          docker-compose -f ./sample-score-website/docker-compose.test-github.yml -p testing up --build --exit-code-from api-test
          echo --- Completed test cases ---
      - name: Send slack notification
        if: always()
        uses: hkma08/sample-score-website@develop    
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: '#deployment'
          status: ${{ job.status }}
          success_text: Build completed successfully
          failure_text: 'Build failed'
          cancelled_text: 'Build was cancelled'
          fields: |
            [{ "title": "Repository", "value": "${env.GITHUB_REPOSITORY}", "short": true },
            { "title": "Branch", "value": "${env.BRANCH}", "short": true },
            { "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]